### PR TITLE
Add support for newer fastapi

### PR DESCRIPTION
**Pull request by zmievsa**

### CODE REVIEW

**Comment by feluelle** [comment]
Hey @zmievsa, could you please also port this to the `4.x.x` release series?

We have to pin `fastapi<=0.112.2` in our project because of the same issue.

**Comment by zmievsa** [comment]
@feluelle Hi! Which version of Cadwyn do you have? I remember fixing this problem in 4.x.x. However, I'm ready to fix it ASAP if it is a problem for you right now.

My [tests](https://github.com/zmievsa/cadwyn/actions/runs/11450720554/job/31858698298) indicate otherwise for now though.

**Comment by feluelle** [comment]
Oh, we were on `4.2.2`. Dependabot did not update our version for some reason, sorry 🤷🏼 It seems to have been fixed by updating to `<4.4.0`. I need to look into why `4.4.0` creates empty openapi specs.

**Comment by feluelle** [comment]
Any idea why that could be the case, @zmievsa? Happy to open a new issue for that.

**Comment by zmievsa** [comment]
Please, open a new issue. Any reproducible example would be fine. I'll be able to fix it within less than a day.

**Comment by zmievsa** [comment]
Hi, @feluelle !

Did the issue with `paths` resolve on its own or do you still need help? I have put aside time for it today so I can help as soon as you post the reproducible example. No rush though :)

**Comment by feluelle** [comment]
Hmm, so it seems that this is a general issue in my fastapi app. The cadwyn `__call__` function does not seem to get called which should call `_cadwyn_initialize()`. Any idea why that could be?

**Comment by feluelle** [comment]
https://github.com/zmievsa/cadwyn/issues/229

**Pull request merged**
