### PR TITLE
Add root path to servers list of OpenAPI spec.

### PR DESCRIPTION
**Pull request by OD-tpeko**
Normally, FastAPI includes the root path in the OpenAPI spec if not contained in the user defined servers list.
This helps to support sub-apps and APIs behind a reverse proxy.
This PR implements that behavior for cadwyn.

### CODE REVIEW

**Comment by zmievsa** [comment]
This insert looks quite scary. Is this the way it's implemented in FastAPI?

Additionally, the tests are failing because of lack of coverage of the branch where "if" is False. You can check that using `make test` or by looking at the CI above.

**Comment by OD-tpeko** [comment]
Yeah, it is basically copied 1:1 from FastAPI. Maybe it is worth thinking about not inserting the root path but merge it only on demand as argument for openapi.json generation.

Thanks for the coverage explanation, was already wondering why no 100% since there is no else branch, but got it.

**Comment by zmievsa** [comment]
Thanks! I'll review it shortly. 

If you need any other help integrating Cadwyn into your project or if you have any feedback (positive or negative) regarding Cadwyn -- feel free to share it in an issue or in [discord](https://discord.gg/yRmcWF7rxE)/[telegram](t.me/zmievsa).

**Comment by zmievsa** [comment]
Thanks for your contribution!

**Comment by zmievsa** [comment]
Released: https://pypi.org/project/cadwyn/4.2.2/

**Pull request merged**
